### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by shardator** [SteveBenz/ScrapMechanicLogicGateSimulator#3]
Hey, I have 0 knowledge of JavaScript, Node.JS, Typescript code installation. I'd like to help my son with building something in Scrap Mechanic, and would like to give a try to this tool. However I fail to install it (trying on Linux in WSL):

```
~/ScrapMechanicLogicGateSimulator/konva-react$ sudo npm install
loadDep:webpack-dev-serve ▌ ╢████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! Linux 4.4.0-19041-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
WARN engine webpack-dev-server@4.11.1: wanted: {"node":">= 12.13.0"} (current: {"node":"8.10.0","npm":"3.5.2"})

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ianas/ScrapMechanicLogicGateSimulator/konva-react/npm-debug.log
```
Attached debug log:

[npm-debug.log](https://github.com/SteveBenz/ScrapMechanicLogicGateSimulator/files/10047055/npm-debug.log)

**Comment by SteveBenz** [comment]
If you just want to use it, you can go here: https://stevebenz.github.io/ScrapMechanicLogicGateSimulator/
